# Generated by Django 3.2.6 on 2022-06-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetterRecipients',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
