# Generated by Django 3.2.6 on 2022-06-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
