# Generated by Django 3.2.6 on 2022-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20220622_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
