# Generated by Django 3.2.6 on 2022-06-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='static/images/default.png', upload_to='static/images/'),
        ),
    ]
