# Generated by Django 3.2.6 on 2022-06-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
