# Generated by Django 3.2.6 on 2022-06-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0009_auto_20220627_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='pic',
            new_name='pi',
        ),
    ]
