# Generated by Django 3.2.6 on 2022-06-27 10:39

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0010_rename_pic_neighbourhood_pi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
