# Generated by Django 3.2.6 on 2022-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0011_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
