# Generated by Django 3.2.6 on 2022-06-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0014_auto_20220627_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='pi',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
